## Tutorial: how to import the data and visualise them

In [1]:
import numpy as np
import random
import networkx as nx
#from tree import FamilyTree
from data_handler import ParticleDataset

from jupyterthemes import jtplot
jtplot.style(theme='oceans16')

INFO: Using numpy backend


## The dataset

The dataset is structured as a Pytorch dataset. The two inputs are the path for the data directory and the signal name (this depends on the physics event we are interested in and it is chosen once the data is generated).

The dataset spits each event as dictionary which contains a graphicle object and a hyperbolic coordinates array for each of the algorithm tree (AntiKt, CA and Kt) and for the MC truth.

In [2]:
dataset = ParticleDataset('data/test4', 'signal')
event = dataset[0]

In [3]:
event.keys()

dict_keys(['MC_graph', 'aKt_graph', 'CA_graph', 'Kt_graph'])

In [4]:
# get the graph from the dict, e.g. get the CA_graph
ca = event['CA_graph']

# create the networkx object
G = nx.Graph()
G.add_edges_from(ca.edges)

In [5]:
# get the adjacency matrix from the networkx object
A = nx.adjacency_matrix(G)
print(A.todense())

[[0 1 0 ... 1 1 1]
 [1 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 ...
 [1 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]]
